#!/usr/bin/with-contenv bash

DISPLAY=${DISPLAY:-10}
XPRA_PORT=${XPRA_PORT:-3388}

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

exec \
	s6-setuidgid abc /usr/bin/xpra start ":${DISPLAY}" --daemon=no --bind-tcp=0.0.0.0:"${XPRA_PORT}"
