#!/usr/bin/with-contenv bash

DISPLAY=${DISPLAY:-10}

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

export DISPLAY=":${DISPLAY}"
exec \
	s6-setuidgid abc /opt/google/chrome/chrome --no-sandbox
